!==============================================================================!
  subroutine Split_String(Foul, string, delimiter, substrings, substring_count)
!------------------------------------------------------------------------------!
!   Helper function
!   Splits the supplied string along a delimiter
!------------------------------------------------------------------------------!
!   Input:
!   string:    Variable-length character string that is to be split
!   delimiter: Character along which to split
!
!   Output:
!   substrings:      Array of substrings generated by split operation
!   substring_count: Number of substrings generated
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  class(Foul_Type)          :: Foul
  character(*), intent(in)  :: string
  character,    intent(in)  :: delimiter
  character(*), intent(out) :: substrings(*)
  integer,      intent(out) :: substring_count
!-----------------------------------[Locals]-----------------------------------!
  integer :: start_pos, end_pos
!------------------------[Avoid unused parent warning]-------------------------!
  Unused(Foul)
!==============================================================================!

  start_pos  = 1
  substring_count = 0

  do
    end_pos = index(string(start_pos:), delimiter)

    substring_count = substring_count + 1

    if(end_pos == 0) then
      substrings(substring_count) = string(start_pos:)
      exit
    else
      substrings(substring_count) = string(start_pos : start_pos + end_pos - 2)
      start_pos = start_pos + end_pos
    end if
  end do

  end subroutine

